[Frontend] TAPP-116: create shared file-related functions for components
uoft-tapp/tapp pull request #117
Opened 2019-05-24 23:10 UTC by michellemtchai

Please refer to issue #116 for details.

2019-05-29 22:12 UTC, michellemtchai commented
Please check if this code works on Safari if you have a Mac.

2019-06-06 19:32 UTC, dingtaoliu requested changes
Just one small change, everything else looks good!  I like how generalized these functions are, good work!

2019-06-06 19:32 UTC, dingtaoliu commented on frontend/src/lib/fileManager.js
> +    } else {
We can pull component.value out of the if block and get rid of the else to be more concise

2019-06-07 02:08 UTC, michellemtchai commented on frontend/src/lib/fileManager.js
> +    } else {
I've fixed the redundancy. Thanks.

2019-06-07 03:34 UTC, merged